branch-defaults:
  lw-devel:
    environment: LessestWrong
  ea-dev:
    environment: EAForum-Staging-2
global:
  # Use deploy.sh to change this to the correct application name
  application_name: APPLICATION_NAME
  branch: null
  default_platform: Docker
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
