name: Run Unit Tests
on:
  push:
  pull_request:
    branches-ignore:
      - ea-deploy
jobs:
  runLint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn install --frozen-lockfile
    - run: yarn run eslint

  runTypecheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn install --frozen-lockfile
    - run: yarn run tsc

  runUnitTests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn install --frozen-lockfile
    - run: yarn run unit-ci

  runIntegrationTests:
    concurrency: integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - run: yarn install --frozen-lockfile
    - name: Seed integration database
      if: failure()
      env:
        TESTING_DB_URL: ${{ secrets.TESTING_DB_URL }}
        PG_URL: ${{ secrets.PG_URL }}
      run: yarn seed-integration-db
    - name: yarn run integration-ci
      env:
        PG_URL: ${{ secrets.PG_URL }}
        NODE_OPTIONS: "--max_old_space_size=4096"
      run: yarn run integration-ci
